### ISSUE TITLE
certain mp4 is not displayed

### ISSUE THREAD

**Issue by zqwei** [jupyterlab/jupyterlab-mp4#2]
I tried to display mp4 file generated in python, but it does not work. Here is the code for movie

```python
from skvideo.io import vwrite
a = np.random.randn(100, 720, 1280)*255
vwrite('random.mp4',a.astype('uint8'))
```

Many thanks.

**Comment by ian-r-rose** [comment]
Hi @zqwei, this appears to be a problem with the video file, or at least the browser's ability to render it. Neither Firefox nor Chrome have the ability to view that file (opened separately from JupyterLab), as far as I can tell. Perhaps it is a bug in `skvideo`?

**Comment by zqwei** [comment]
Yes, you are right. I tried other encoder such as H264, but it does not work either, probably this is an issue for chrome.
